name: 'Format tags semver'
description: 'Generate multiple output formats of a tag in semver standard'
inputs:
  tag:
    description: 'tag value'
    required: true
    default: 'v0.0.0'
outputs:
  raw:
    description: 'raw'
  major:
    description: 'major'
  minor:
    description: 'minor'
  patch:
    description: 'patch'
  release:
    description: 'release'
  version:
    description: 'patch'
runs:
  using: 'node16'
  main: 'dist/index.js'
